### ISSUE TITLE
Connecting to BOSH

### ISSUE THREAD

**Issue by RobiD** [cloudfoundry-community/bosh_exporter#1]
When connecting to BOSH, I am getting:
```json
x509: cannot validate certificate for X.X.X.X because it doesn't contain any IP SANs
```

I have executed bosh_exporter command like this:  
/var/go/bin/bosh_exporter -bosh.url $BOSH_EXPORTER_BOSH_URL \
  -bosh.username $BOSH_EXPORTER_BOSH_USERNAME \
  -bosh.password $BOSH_EXPORTER_BOSH_PASSWORD

I have also added bosh.ca-cert-file flag at the end of command and placed a valid BOSH certificate, but I am getting the same error message. Any idea?

**Comment by frodenas** [comment]
The certificates must be created setting a Subject Alternative Name (SAN) with the IP address of the BOSH director, otherwise, you will get the `cannot validate certificate for X.X.X.X because it doesn't contain any IP SANs` error message.

This exporter is using the golang [bosh-cli](https://github.com/cloudfoundry/bosh-cli/tree/master/director) director libraries, and unfortunately, there is no way to disable this validation (without creating my own bosh golang library). More details at https://github.com/cloudfoundry/bosh-cli/issues/19.

Here there is an example of how to create valid BOSH certificates: https://github.com/cloudfoundry/bosh-lite/blob/master/ca/generate.sh

**Comment by RobiD** [comment]
@frodenas, thanks! :-) I will try that out and come back to you with the result.

**Comment by RobiD** [comment]
We have created a certificate by setting a Subject Alternative Name (SAN) with the IP address of the BOSH director, following the script you have suggested: https://github.com/cloudfoundry/bosh-lite/blob/master/ca/generate.sh (of course we have modified the line with ip variable, where we have put our Bosh Directors IP address).

The certificates have been successfully created. In fact, when we execute the script, the following files are being generated:
* ca.crt
* ca.key
* ca.srl
* director.crt
* director.key

We have then placed the certificates on the Docker instance, where the bosh-exporter is running, but we are still getting the same error message:
```
x509: cannot validate certificate for 10.17.175.11 because it doesn't contain any IP SANs
```
@frodenas, any idea what we could be doing wrong here?

**Comment by frodenas** [comment]
@RobiD  Have you redeployed your BOSH director with the `director.crt` and `director.key` files?

I've added a section at the FAQ explaining how to generate/deploy the SSL Certificates: https://github.com/cloudfoundry-community/bosh_exporter/blob/master/FAQ.md#how-can-i-get-the-bosh-ca-certificate

**Comment by RobiD** [comment]
@frodenas, thanks for your prompt answer and a link to FAQ! I guess, this is the step we have been missing. We will try to redeploy BOSH early next week using director.crt and director.key files. Will keep you updated.

**Comment by frodenas** [comment]
ok, I'll keep this issue open until you test it.

**Comment by shinji62** [comment]
I try it, and this fix the issue.
Just need to follow the bosh.io docs and add the cert into bosh exporter using the right properties.

**Comment by frodenas** [comment]
Closing this. @RobiD please reopen if it doesn't work or you need some help with the ssl keys.
